services:
  - type: web
    name: honor-labs-app
    runtime: docker
    envVars:
      - key: WC_SITE_URL
        sync: false
      - key: WC_CONSUMER_KEY
        sync: false
      - key: WC_CONSUMER_SECRET
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: APP_USERS
        sync: false
